version: "3.9"

services:
   wordpress-init:
    image: wordpress:cli-php8.4
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    user: root
    command: ["/bin/bash", "/tmp/init.sh"]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WP_ADMIN_USER: ${WP_USERNAME}
      WP_ADMIN_PASSWORD: ${WP_PASSWORD}
      WP_TITLE: "New wordpress blog"
      WP_ADMIN_EMAIL: admin@example.com
      WP_LOCALE: ${WP_LOCALE}
      WP_INIT: "true"
      WP_URL: "${WP_SCHEME}://${WP_DOMAINNAME}"
      WORDPRESS_VERSION: ${WORDPRESS_VERSION}

    volumes:
      - wordpress:/var/www/html:rw
      - ./init-alpine.sh:/tmp/init.sh:ro
      - ./cache-config.json:/tmp/cache-config.json:ro

   memcached:
    image: memcached:latest
    restart: always

   wordpress:
    #image: ghcr.io/shesselink81/wordpress-alpine:v6.9.0.5
    build: .
    container_name: wp-fpm
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      wordpress-init:
        condition: service_completed_successfully
      memcached:
        condition: service_started
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

    volumes:
      - wordpress:/var/www/html:rw
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/zz-custom.conf:ro
      - ./php.ini:/usr/local/etc/php/conf.d/zz-custom.ini:ro

   db:
    image: mariadb:12.1.2
    container_name: wp-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

   nginx:
    #image: ghcr.io/shesselink81/nginx-alpine:v6.9.0.4
    build:
      context: ./nginx/
    container_name: wp-nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    ports:
      - "8088:80"
      - "9443:443"
    volumes:
      - wordpress:/var/www/html:rw
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
      #- ./nginx/ssl:/etc/nginx/ssl:ro
  
  #  wordpress-cli:
  #   image: wordpress:cli-php8.4
  #   depends_on:
  #     db:
  #       condition: service_started
  #   restart: "always"
  #   user: www-data
  #   command: ["/bin/bash", "-c", "sleep infinity"]
  #   environment:
  #     WP_DB_HOST: db
  #     WP_DB_USER: ${MYSQL_USER}
  #     WP_DB_PASSWORD: ${MYSQL_PASSWORD}
  #     WP_DB_NAME: ${MYSQL_DATABASE}
  #     WP_URL: "${WP_SCHEME}://${WP_DOMAINNAME}"
  #     WORDPRESS_VERSION: ${WORDPRESS_VERSION}
  #   volumes:
  #     - wordpress:/var/www/html:rw
volumes:
  wordpress:
  db_data:
