apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress-alpine.fullname" . }}-wp-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.wordpress.size }}