apiVersion: v1
entries:
  wordpress-alpine:
  - apiVersion: v2
    appVersion: 6.9.0
    created: "2025-12-20T01:30:54.2777836+01:00"
    dependencies:
    - condition: memcached.enabled
      name: memcached
      repository: oci://registry-1.docker.io/cloudpirates
      version: 0.8.0
    description: WordPress FPM + Nginx + Init + MariaDB (alpine)
    digest: 891880a7a4557695fee911deae86f5013cd60982b56f76c4f4776884e7a6eb7d
    home: https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    icon: https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wordpress/app.png
    maintainers:
    - name: shesselink81
    name: wordpress-alpine
    sources:
    - https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    type: application
    urls:
    - wordpress-alpine-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: 6.9.0
    created: "2025-12-20T01:30:54.2751142+01:00"
    dependencies:
    - condition: memcached.enabled
      name: memcached
      repository: oci://registry-1.docker.io/cloudpirates
      version: 0.8.0
    description: WordPress FPM + Nginx + Init + MariaDB (alpine)
    digest: 3df7310b5463bd57e304c23323b4eae3771f3f409a7d3ef4ffbca910d11f19cb
    home: https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    icon: https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wordpress/app.png
    maintainers:
    - name: shesselink81
    name: wordpress-alpine
    sources:
    - https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    type: application
    urls:
    - wordpress-alpine-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: 6.9.0
    created: "2025-12-20T01:30:54.2511459+01:00"
    dependencies:
    - condition: memcached.enabled
      name: memcached
      repository: oci://registry-1.docker.io/cloudpirates
      version: 0.8.0
    description: WordPress FPM + Nginx + Init + MariaDB (alpine)
    digest: 0e814b10603b2c32b7f9ed5dbadc2864336d374d2666493a667391853f0dac53
    home: https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    icon: https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wordpress/app.png
    maintainers:
    - name: shesselink81
    name: wordpress-alpine
    sources:
    - https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    type: application
    urls:
    - wordpress-alpine-0.1.4.tgz
    version: 0.1.4
generated: "2025-12-20T01:30:54.2207217+01:00"
