apiVersion: v1
entries:
  wordpress-alpine:
  - apiVersion: v2
    appVersion: 6.9.0
    created: "2025-12-19T21:01:52.7847363+01:00"
    dependencies:
    - condition: memcached.enabled
      name: memcached
      repository: oci://registry-1.docker.io/cloudpirates
      version: 0.8.0
    description: WordPress FPM + Nginx + Init + MariaDB (alpine)
    digest: 0e814b10603b2c32b7f9ed5dbadc2864336d374d2666493a667391853f0dac53
    home: https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    icon: https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wordpress/app.png
    maintainers:
    - name: shesselink81
    name: wordpress-alpine
    sources:
    - https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    type: application
    urls:
    - wordpress-alpine-0.1.4.tgz
    version: 0.1.4
generated: "2025-12-19T21:01:52.7812497+01:00"
