apiVersion: v1
entries:
  memcached:
  - annotations:
      artifacthub.io/category: database
      artifacthub.io/changes: |2
            - kind: changed
              description: "Update charts/memcached/values.yaml memcached (#710)"
              links:
                - name: "Commit 9a0f0bc"
                  url: "https://github.com/CloudPirates-io/helm-charts/commit/9a0f0bc"
      artifacthub.io/containsSecurityUpdates: "false"
      artifacthub.io/links: |
        - name: Memcached
          url: https://memcached.org
        - name: Helm Chart
          url: https://github.com/CloudPirates-io/helm-charts/tree/main/charts/memcached
        - name: Maintainer CloudPirates
          url: https://www.cloudpirates.io
      artifacthub.io/signKey: |
        fingerprint: 6917f1a88c122cbb1de5aa55457752135bdcf95a
        url: https://raw.githubusercontent.com/CloudPirates-io/helm-charts/refs/heads/main/cosign.pub
      license: Apache-2.0
    apiVersion: v2
    appVersion: 1.6.39
    created: "2025-12-19T19:23:02.4958781+01:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/cloudpirates
      version: 2.x.x
    description: Memcached is an in-memory key-value store for small chunks of arbitrary
      data (strings, objects) from results of database calls, API calls, or page rendering.
    digest: a2582827fe32fa968e8ed0694d80466d7997b6fd1457476d8eeda5cf2958aec0
    home: https://memcached.org
    icon: https://a.storyblok.com/f/143071/512x512/0faa83eb34/memcached-logo.svg
    keywords:
    - memcached
    - cache
    - in-memory
    - key-value
    - distributed
    maintainers:
    - email: hello@cloudpirates.io
      name: CloudPirates GmbH & Co. KG
      url: https://www.cloudpirates.io
    name: memcached
    sources:
    - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/memcached
    - https://github.com/memcached/memcached
    type: application
    urls:
    - charts/memcached-0.8.0.tgz
    version: 0.8.0
  wordpress-alpine:
  - apiVersion: v2
    appVersion: 6.9.0
    created: "2025-12-19T19:23:02.493778+01:00"
    dependencies:
    - condition: memcached.enabled
      name: memcached
      repository: oci://registry-1.docker.io/cloudpirates
      version: 0.8.0
    description: WordPress FPM + Nginx + Init + MariaDB (alpine)
    digest: e8cb057684beeee0cf120f8e22a8e62e98a287d0d6698cc11eb7bb1d4abb6dc6
    home: https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    icon: https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wordpress/app.png
    maintainers:
    - name: shesselink81
    name: wordpress-alpine
    sources:
    - https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    type: application
    urls:
    - wordpress-alpine-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: 6.9.0
    created: "2025-12-19T19:23:02.4900826+01:00"
    dependencies:
    - condition: memcached.enabled
      name: memcached
      repository: oci://registry-1.docker.io/cloudpirates
      version: 0.8.0
    description: WordPress FPM + Nginx + Init + MariaDB (alpine)
    digest: dfe2d3dbda75a8302136546636c13cf53100a6dc1cf95a3e1e7e1612d7f7763b
    home: https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    icon: https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wordpress/app.png
    maintainers:
    - name: shesselink81
    name: wordpress-alpine
    sources:
    - https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    type: application
    urls:
    - wordpress-alpine-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 6.9.0
    created: "2025-12-19T19:23:02.486163+01:00"
    dependencies:
    - condition: memcached.enabled
      name: memcached
      repository: oci://registry-1.docker.io/cloudpirates
      version: 0.8.0
    description: WordPress FPM + Nginx + Init + MariaDB (alpine)
    digest: 759e9740c8de466e509f2056f9aa4bb27faaad82f0d103010207682693beab8a
    home: https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    icon: https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wordpress/app.png
    maintainers:
    - name: shesselink81
    name: wordpress-alpine
    sources:
    - https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    type: application
    urls:
    - wordpress-alpine-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 6.9.0
    created: "2025-12-19T19:23:02.4835589+01:00"
    dependencies:
    - condition: memcached.enabled
      name: memcached
      repository: oci://registry-1.docker.io/cloudpirates
      version: 0.7.1
    description: WordPress FPM + Nginx + Init + MariaDB (alpine)
    digest: 928fb98a0291af2d01456ea6f12446cc22463bc96a3248506de62ce400bea0a4
    home: https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    icon: https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wordpress/app.png
    maintainers:
    - name: shesselink81
    name: wordpress-alpine
    sources:
    - https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
    type: application
    urls:
    - wordpress-alpine-0.1.1.tgz
    version: 0.1.1
generated: "2025-12-19T19:23:02.4783019+01:00"
