apiVersion: v2
name: wordpress-alpine
version: 1.2.4
appVersion: "6.9.1" # renovate: image=docker.io/wordpress
icon: https://raw.githubusercontent.com/slydlake/helm-charts/refs/heads/main/charts/wordpress/app.png
home: https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
maintainers:
  - name: shesselink81
sources:
  - https://github.com/shesselink81/wordpress-apache/tree/main/wordpress-alpine/chart
description: WordPress FPM + Nginx + Init + MariaDB (alpine)
type: application
dependencies:
  - condition: memcached.enabled
    name: memcached
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.8.0
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.10.1