[www]
pm = dynamic
pm.max_children = 20
pm.start_servers = 1
pm.min_spare_servers = 0
pm.max_spare_servers = 10
pm.max_requests = 500

; Better performance & stability
request_terminate_timeout = 300
request_slowlog_timeout = 10

; Logging
slowlog = /proc/self/fd/2

; Fast CGI handling
catch_workers_output = yes
