image:
  fpm: ghcr.io/shesselink81/wordpress-alpine:7.0.2.3
  nginx: ghcr.io/shesselink81/nginx-alpine:7.0.2.3
  init: wordpress:cli-php8.4

imagePullSecrets: []

env:
  wp:
    scheme: https
    domainname: wordpress.local
    url: "${scheme}://${domainname}"
    version: "7.0.2"
    locale: en_US
    title: "My WordPress Site"
    admin_user: admin
    debug: "false"

hostAliases:
  enabled: false
  entries:
    - ip: "10.10.10.10"
      hostnames:
        - "wordpress.local"

wordpress:
  init:
    enabled: true
  resources:
    requests:
       memory: "128Mi"
       cpu: "50m"
    limits:
       memory: "512Mi"
       cpu: "300m"
  nodeSelector: {}
  auth:
    username: db-user
    existingSecret: "wordpress-secrets"
    secretKeys:
      wpPasswordKey: wordpress.password
      rootPasswordKey: db.root.password
      userPasswordKey: db.password

ingress:
  enabled: false
  className: "traefik"
  annotations: {}
  hosts:
    - host: wordpress.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  useHttpsBackend: false
  extraRules: []

httproute:
  enabled: false
  gateway:
    name: traefik-gateway
    namespace: traefik
  hostnames:
    - wordpress.local
    - www.wordpress.local
  path: /

persistence:
  wordpress:
    enabled: true
    size: 5Gi
    existingClaim: ""
    keep: true

mariadb:
  enabled: true
  initdbScriptsConfigMap: ""
  auth:
    enabled: true
    rootPassword: ""
    database: "wp_db"
    username: "db-user"
    password: ""
    existingSecret: "wordpress-secrets"
    allowEmptyRootPassword: "false"
    secretKeys:
      rootPasswordKey: db.root.password
      userPasswordKey: db.password
  nodeSelector: {}
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 1Gi
  resources:
    requests:
       memory: "128Mi"
       cpu: "100m"
    limits:
       memory: "350Mi"
       cpu: "500m"

externalDatabase:
  database: null
  host: null
  secretKeys:
    userPasswordKey: db.password

nginx:
  nodeSelector: {}
  resources:
    requests:
       memory: "32Mi"
       cpu: "10m"
    limits:
       memory: "96Mi"
       cpu: "200m"
  service:
    port: 80

memcached:
  enabled: true
  createConfig: true
  nameOverride: ""
  fullnameOverride: ""
  resources:
    requests:
       memory: "15Mi"
       cpu: "5m"
    limits:
       memory: "90Mi"
       cpu: "100m"

secrets:
  name: ""
  wordpress:
    password: "admin"
  mariadb:
    rootPassword: "rootpassword"
    userPassword: "userpassword"
  stringData: {}
  data: {}