apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress-alpine.fullname" . }}-db-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.db.size }}
    reclaimPolicy: Retain
    