apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wordpress-alpine.fullname" . }}-db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.image.db }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpass"
            - name: MYSQL_USER
              value: {{ .Values.env.mysql.user | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.env.mysql.password | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.env.mysql.database | quote }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: dbdata
      volumes:
        - name: dbdata
          persistentVolumeClaim:
            claimName: {{ include "wordpress-alpine.dbpvcName" . }}