apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-alpine.fullname" . }}-db
spec:
  selector:
    app: db
  ports:
    - port: {{ .Values.service.db.port }}
      targetPort: {{ .Values.service.db.port }}
      protocol: TCP