apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-alpine.fullname" . }}-nginx
spec:
  selector:
    app: nginx
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.port }}
      protocol: TCP