{{- $createSecret := or (and .Values.wordpress.auth.existingSecret (ne .Values.wordpress.auth.existingSecret "")) (and .Values.mariadb.auth.existingSecret (ne .Values.mariadb.auth.existingSecret "")) }}
{{- if $createSecret }}
{{- $secretName := .Values.secrets.name | default (.Values.wordpress.auth.existingSecret | default (include "wordpress-alpine.fullname" . | printf "%s-secrets")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
{{ include "wordpress-alpine.labels" . | indent 4 }}
type: Opaque
stringData:
{{- if and .Values.wordpress.auth.existingSecret (ne .Values.wordpress.auth.existingSecret "") }}
  {{ .Values.wordpress.auth.secretKeys.wpPasswordKey }}: {{ .Values.secrets.wordpress.password | default "changeme" | quote }}
{{- end }}
{{- if and .Values.wordpress.auth.existingSecret (ne .Values.wordpress.auth.existingSecret "") }}
  {{ .Values.wordpress.auth.secretKeys.rootPasswordKey }}: {{ .Values.secrets.mariadb.rootPassword | default "changeme" | quote }}
  {{ .Values.wordpress.auth.secretKeys.userPasswordKey }}: {{ .Values.secrets.mariadb.userPassword | default "changeme" | quote }}
{{- end }}
{{- if .Values.secrets.stringData }}
{{- range $key, $val := .Values.secrets.stringData }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}
{{- if .Values.secrets.data }}
data:
{{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: {{ $val }}
{{- end }}
{{- end }}
{{- end }}
