apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-alpine.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "wordpress-alpine.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "wordpress-alpine.labels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- if .Values.hostAliases.enabled }}
      hostAliases:
        {{- range .Values.hostAliases.entries }}
        - ip: {{ .ip | quote }}
          hostnames:
            {{- range .hostnames }}
            - {{ . | quote }}
            {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.wordpress.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init
          image: {{ .Values.image.init }}
          command: ["/bin/bash", "/tmp/init.sh"]
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ if .Values.externalDatabase.host }}{{ .Values.externalDatabase.host }}{{ else }}{{ include "wordpress-alpine.mariadb.fullname" . | default "mariadb" }}{{ end }}
            - name: MEMCACHED_HOST
              value: {{ include "wordpress-alpine.memcached.fullname" . }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.wordpress.auth.username | quote }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpress.auth.existingSecret | quote }}
                  key: {{ .Values.wordpress.auth.secretKeys.userPasswordKey }}
            - name: WORDPRESS_DB_NAME
              value: {{ if .Values.externalDatabase.database }}{{ .Values.externalDatabase.database | quote }}{{ else }}{{ .Values.mariadb.auth.database | quote }}{{ end }}
            - name: WP_URL
              value: "{{ .Values.env.wp.scheme }}://{{ .Values.env.wp.domainname }}"
            - name: WORDPRESS_VERSION
              value: {{ .Values.env.wp.version | quote }}
            - name: WP_LOCALE
              value: {{ .Values.env.wp.locale | quote }}
            - name: WP_TITLE
              value: {{ .Values.env.wp.title | quote }}
            - name: WP_ADMIN_USER
              value: {{ .Values.env.wp.admin_user | quote }}
            - name: WP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpress.auth.existingSecret | quote }}
                  key: {{ .Values.wordpress.auth.secretKeys.wpPasswordKey }}
            - name: WP_ADMIN_EMAIL
              value: admin@{{ .Values.env.wp.domainname }}
          volumeMounts:
            - name: wordpress
              mountPath: /var/www/html
            - name: init-script
              mountPath: /tmp/init.sh
              subPath: init.sh
            - name: cache-config
              mountPath: /tmp/cache-config.json
              subPath: cache-config.json
      containers:
        - name: fpm
          image: {{ .Values.image.fpm }}
          ports:
            - containerPort: 9000
              protocol: TCP
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ if .Values.externalDatabase.host }}{{ .Values.externalDatabase.host }}{{ else }}{{ include "wordpress-alpine.mariadb.fullname" . | default "mariadb" }}{{ end }}
            - name: MEMCACHED_HOST
              value: {{ include "wordpress-alpine.memcached.fullname" . }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.wordpress.auth.username | quote }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpress.auth.existingSecret | quote }}
                  key: {{ .Values.wordpress.auth.secretKeys.userPasswordKey }}
            - name: WORDPRESS_DB_NAME
              value: {{ if .Values.externalDatabase.database }}{{ .Values.externalDatabase.database | quote }}{{ else }}{{ .Values.mariadb.auth.database | quote }}{{ end }}
            - name: WP_URL
              value: "{{ .Values.env.wp.scheme }}://{{ .Values.env.wp.domainname }}"
            - name: WORDPRESS_VERSION
              value: {{ .Values.env.wp.version | quote }}
            - name: WP_LOCALE
              value: {{ .Values.env.wp.locale | quote }}
            - name: WP_TITLE
              value: {{ .Values.env.wp.title | quote }}
            - name: WP_ADMIN_USER
              value: {{ .Values.env.wp.admin_user | quote }}
            - name: WP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpress.auth.existingSecret | quote }}
                  key: {{ .Values.wordpress.auth.secretKeys.wpPasswordKey }}
            - name: WP_ADMIN_EMAIL
              value: admin@{{ .Values.env.wp.domainname }}
          {{- with .Values.wordpress.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress
            - mountPath: /usr/local/etc/php/php.ini
              name: php-config
              subPath: php.ini
            - mountPath: /usr/local/etc/php/conf.d/php-fpm.conf
              name: php-config
              subPath: php-fpm.conf
        - name: nginx
          image: {{ .Values.image.nginx }}
          securityContext:
            runAsUser: 101
            runAsGroup: 101
          ports:
            - containerPort: {{ .Values.nginx.service.port }}
          {{- with .Values.nginx.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginxconf
              subPath: default.conf
            - mountPath: /etc/nginx/nginx.conf
              name: nginxconf
              subPath: nginx.conf
      volumes:
        - name: wordpress
          persistentVolumeClaim:
            claimName: {{ include "wordpress-alpine.pvcName" . }}
        - name: init-script
          configMap:
            name: {{ include "wordpress-alpine.fullname" . }}-init-config
        - name: php-config
          configMap:
            name: {{ include "wordpress-alpine.fullname" . }}-php-config
        - name: cache-config
          configMap:
            name: {{ include "wordpress-alpine.fullname" . }}-cache-config
        - name: nginxconf
          configMap:
            name: {{ include "wordpress-alpine.fullname" . }}-nginx-config
