apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-alpine.fullname" . }}-fpm
spec:
  selector:
    matchLabels:
      app: wordpress-fpm
  template:
    metadata:
      labels:
        app: wordpress-fpm
    spec:
      initContainers:
        - name: init
          image: {{ .Values.image.init }}
          command: ["/bin/bash", "/tmp/init.sh"]
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ include "wordpress-alpine.mariadb.fullname" . | default "mariadb" }}
            - name: MEMCACHED_HOST
              value: {{ include "wordpress-alpine.memcached.fullname" . }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.mariadb.auth.username | quote }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mariadb.auth.existingSecret | quote }}
                  key: {{ .Values.mariadb.auth.secretKeys.userPasswordKey }}           
            # - name: WORDPRESS_DB_PASSWORD
            #   value: {{ .Values.mariadb.auth.password | quote }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.mariadb.auth.database | quote }}
            - name: WP_URL
              value: "{{ .Values.env.wp.scheme }}://{{ .Values.env.wp.domainname }}"
            - name: WORDPRESS_VERSION
              value: {{ .Values.env.wp.version | quote }}
            - name: WP_LOCALE
              value: {{ .Values.env.wp.locale | quote }}
            - name: WP_TITLE
              value: {{ .Values.env.wp.title | quote }}
            - name: WP_ADMIN_USER
              value: {{ .Values.env.wp.admin_user | quote }}
            - name: WP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.wordpres.auth.existingSecret }}
                  key: {{ .Values.wordpress.auth.secretKeys.wpPasswordKey }}   
            # - name: WP_ADMIN_PASSWORD
            #   value: {{ .Values.env.wp.admin_password | quote }}
            - name: WP_ADMIN_EMAIL
              value: admin@{{ .Values.env.wp.domainname }}
          volumeMounts:
            - name: wordpress
              mountPath: /var/www/html
            - name: init-script
              mountPath: /tmp/init.sh
              subPath: init.sh
      containers:
        - name: fpm
          image: {{ .Values.image.fpm }}
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ include "wordpress-alpine.mariadb.fullname" . | default "mariadb" }}
            - name: MEMCACHED_HOST
              value: {{ include "wordpress-alpine.memcached.fullname" . }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.mariadb.auth.username | quote }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ .Values.mariadb.auth.password | quote }}
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.mariadb.auth.database | quote }}
            - name: WP_URL
              value: "{{ .Values.env.wp.scheme }}://{{ .Values.env.wp.domainname }}"
            - name: WORDPRESS_VERSION
              value: {{ .Values.env.wp.version | quote }}
            - name: WP_LOCALE
              value: {{ .Values.env.wp.locale | quote }}
            - name: WP_TITLE
              value: {{ .Values.env.wp.title | quote }}
            - name: WP_ADMIN_USER
              value: {{ .Values.env.wp.admin_user | quote }}
            - name: WP_ADMIN_PASSWORD
              value: {{ .Values.env.wp.admin_password | quote }}
            - name: WP_ADMIN_EMAIL
              value: admin@{{ .Values.env.wp.domainname }}
          {{- with .Values.wordpress.resources }}    
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}  
          volumeMounts:
            - mountPath: /var/www/html
              name: wordpress
            - mountPath: /usr/local/etc/php/php.ini
              name: php-config
              subPath: php.ini
            - mountPath: /usr/local/etc/php/conf.d/php-fpm.conf
              name: php-config
              subPath: php-fpm.conf
      volumes:
        - name: wordpress
          persistentVolumeClaim:
            claimName: {{ include "wordpress-alpine.pvcName" . }}
        - name: init-script
          configMap:
            name: {{ include "wordpress-alpine.fullname" . }}-init-config
        - name: php-config
          configMap:
            name: {{ include "wordpress-alpine.fullname" . }}-php-config